{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "A_AddressEmailAddress",
        "Service": "/MyApplication/Services/BusinessPartnerA2X.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "AddressID": "#Control:AddressID/#Value",
        "Person": "#Control:Person/#Value",
        "OrdinalNumber": "#Control:OrdinalNumber/#Value",
        "IsDefaultEmailAddress": "#Control:IsDefaultEmailAddress/#Value",
        "EmailAddress": "#Control:EmailAddress/#Value",
        "SearchEmailAddress": "#Control:SearchEmailAddress/#Value",
        "AddressCommunicationRemarkText": "#Control:AddressCommunicationRemarkText/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/MyApplication/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/MyApplication/Actions/UpdateEntityFailureMessage.action"
}