{
    "ParentLink": {
        "Property": "to_FaxNumber",
        "Target": {
            "EntitySet": "A_BPContactToAddress",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/MyApplication/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/MyApplication/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "AddressID": "#Control:AddressID/#Value",
        "Person": "#Control:Person/#Value",
        "OrdinalNumber": "#Control:OrdinalNumber/#Value",
        "IsDefaultFaxNumber": "#Control:IsDefaultFaxNumber/#Value",
        "FaxCountry": "#Control:FaxCountry/#Value",
        "FaxNumber": "#Control:FaxNumber/#Value",
        "FaxNumberExtension": "#Control:FaxNumberExtension/#Value",
        "InternationalFaxNumber": "#Control:InternationalFaxNumber/#Value",
        "AddressCommunicationRemarkText": "#Control:AddressCommunicationRemarkText/#Value"
    },
    "Target": {
        "EntitySet": "A_AddressFaxNumber",
        "Service": "/MyApplication/Services/BusinessPartnerA2X.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}