{
    "CreateLinks": [],
    "OnFailure": "/MyApplication/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/MyApplication/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "RelationshipNumber": "#Control:RelationshipNumber/#Value",
        "BusinessPartnerCompany": "#Control:BusinessPartnerCompany/#Value",
        "BusinessPartnerPerson": "#Control:BusinessPartnerPerson/#Value",
        "ValidityEndDate": "#Control:ValidityEndDate/#Value",
        "AddressID": "#Control:AddressID/#Value",
        "AddressNumber": "#Control:AddressNumber/#Value",
        "AdditionalStreetPrefixName": "#Control:AdditionalStreetPrefixName/#Value",
        "AdditionalStreetSuffixName": "#Control:AdditionalStreetSuffixName/#Value",
        "AddressTimeZone": "#Control:AddressTimeZone/#Value",
        "CareOfName": "#Control:CareOfName/#Value",
        "CityCode": "#Control:CityCode/#Value",
        "CityName": "#Control:CityName/#Value",
        "CompanyPostalCode": "#Control:CompanyPostalCode/#Value",
        "Country": "#Control:Country/#Value",
        "County": "#Control:County/#Value",
        "DeliveryServiceNumber": "#Control:DeliveryServiceNumber/#Value",
        "DeliveryServiceTypeCode": "#Control:DeliveryServiceTypeCode/#Value",
        "District": "#Control:District/#Value",
        "FormOfAddress": "#Control:FormOfAddress/#Value",
        "FullName": "#Control:FullName/#Value",
        "HomeCityName": "#Control:HomeCityName/#Value",
        "HouseNumber": "#Control:HouseNumber/#Value",
        "HouseNumberSupplementText": "#Control:HouseNumberSupplementText/#Value",
        "Language": "#Control:Language/#Value",
        "POBox": "#Control:POBox/#Value",
        "POBoxDeviatingCityName": "#Control:POBoxDeviatingCityName/#Value",
        "POBoxDeviatingCountry": "#Control:POBoxDeviatingCountry/#Value",
        "POBoxDeviatingRegion": "#Control:POBoxDeviatingRegion/#Value",
        "POBoxIsWithoutNumber": "#Control:POBoxIsWithoutNumber/#Value",
        "POBoxLobbyName": "#Control:POBoxLobbyName/#Value",
        "POBoxPostalCode": "#Control:POBoxPostalCode/#Value",
        "Person": "#Control:Person/#Value",
        "PostalCode": "#Control:PostalCode/#Value",
        "PrfrdCommMediumType": "#Control:PrfrdCommMediumType/#Value",
        "Region": "#Control:Region/#Value",
        "StreetName": "#Control:StreetName/#Value",
        "StreetPrefixName": "#Control:StreetPrefixName/#Value",
        "StreetSuffixName": "#Control:StreetSuffixName/#Value",
        "TaxJurisdiction": "#Control:TaxJurisdiction/#Value",
        "TransportZone": "#Control:TransportZone/#Value",
        "AddressRepresentationCode": "#Control:AddressRepresentationCode/#Value",
        "ContactPersonBuilding": "#Control:ContactPersonBuilding/#Value",
        "ContactPersonPrfrdCommMedium": "#Control:ContactPersonPrfrdCommMedium/#Value",
        "ContactRelationshipDepartment": "#Control:ContactRelationshipDepartment/#Value",
        "ContactRelationshipFunction": "#Control:ContactRelationshipFunction/#Value",
        "CorrespondenceShortName": "#Control:CorrespondenceShortName/#Value",
        "Floor": "#Control:Floor/#Value",
        "InhouseMail": "#Control:InhouseMail/#Value",
        "IsDefaultAddress": "#Control:IsDefaultAddress/#Value",
        "RoomNumber": "#Control:RoomNumber/#Value"
    },
    "Target": {
        "EntitySet": "A_BPContactToAddress",
        "Service": "/MyApplication/Services/BusinessPartnerA2X.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}