{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/MyApplication/Pages/BusinessPartnerA2X_A_AddressPhoneNumber/A_AddressPhoneNumber_Create.page",
    "_Type": "Action.Type.Navigation"
}