{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/MyApplication/Pages/BusinessPartnerA2X_A_AddressFaxNumber/A_AddressFaxNumber_Edit.page",
    "_Type": "Action.Type.Navigation"
}